# Generated by Django 4.2.2 on 2023-06-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
