# Generated by Django 4.2.2 on 2023-06-27 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_productmodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
